USE MATRICULA
GO

CREATE PROCEDURE GENERARIDDISTRITO
AS DECLARE @IDDISTRITO CHAR(3)
SET @IDDISTRITO=(SELECT MAX(IDDISTRITO)FROM DISTRITO)
SELECT 'D'+RIGHT('0'+RTRIM(RIGHT(@IDDISTRITO, 2)+1),3)
GO

CREATE PROCEDURE GENERARIDUSUARIO
AS DECLARE @IDUSUARIO CHAR(5)
SET @IDUSUARIO=(SELECT MAX(IDUSUARIO)FROM USUARIO)
SELECT 'USU'+RIGHT('0'+RTRIM(RIGHT(@IDUSUARIO, 2)+1),5)
GO



CREATE PROCEDURE GENERARIDDOCENTE
AS DECLARE @IDDOCENTE CHAR(5)
SET @IDDOCENTE=(SELECT MAX(IDDOCENTE)FROM Docente)
SELECT 'DOC'+RIGHT('0'+RTRIM(RIGHT(@IDDOCENTE, 2)+1),5)
GO


CREATE PROCEDURE DOCENTEZ2
AS DECLARE @IDDOCENTE CHAR(5)
SET @IDDOCENTE=(SELECT MAX(IDDOCENTE)FROM Docente)
SELECT 'DOC'+RIGHT('0'+RTRIM(RIGHT(@IDDOCENTE, 2)+1),5)
if (@IDDOCENTE = 'DOC010' )
begin
SELECT 'DOC'+ RIGHT (RTRIM(RIGHT(@IDDOCENTE, 1)+1),5)
END
ELSE
 BEGIN
   PRINT 'CODIDO MODIFICADO'
end
GO




CREATE PROCEDURE GENERARIDESPECIALIDAD
AS DECLARE @IDESPECIALIDAD CHAR(3)
SET @IDESPECIALIDAD=(SELECT MAX(IdEspecialidad)FROM Especialidad)
SELECT 'E'+RIGHT('0'+RTRIM(RIGHT(@IDESPECIALIDAD, 2)+1),3)
GO
--JL.K

CREATE PROCEDURE GENERARIDTIPO
AS DECLARE @IDTIPO CHAR(3)
SET @IDTIPO=(SELECT MAX(IDTIPO)FROM TipoIngreso)
SELECT 'T'+RIGHT('0'+RTRIM(RIGHT(@IDTIPO, 2)+1),3)
GO

CREATE PROCEDURE GENERARIDMODULOP
AS DECLARE @IDMODULOP CHAR(4) 
SET @IDMODULOP=(SELECT MAX(IDMODULOP)from Modulo_Profesional)
SELECT 'MP'+RIGHT(RTRIM(RIGHT(@IDMODULOP, 2)+1),4)
GO

CREATE PROCEDURE GENERARIDMODULOT
AS DECLARE @IDMODULOT CHAR(4) 
SET @IDMODULOT=(SELECT MAX(IDMODULOT)from Modulo_Transversal)
SELECT 'MT'+RIGHT(RTRIM(RIGHT(@IDMODULOT, 2)+1),4)
GO

CREATE PROCEDURE GENERARIDUNDDIDACP
AS DECLARE @IDUNDDIDACP CHAR(4)
SET @IDUNDDIDACP=(SELECT MAX(IDUNDDIDACP)FROM UndDidactica_Profesional)
SELECT 'UP'+RIGHT(RTRIM(RIGHT(@IDUNDDIDACP, 2)+1),4)
GO

CREATE PROCEDURE GENERARIDUNDDIDACT
AS DECLARE @IDUNDDIDACT CHAR(4)
SET @IDUNDDIDACT=(SELECT MAX(IDUNDDIDACT)FROM UndDidactica_Transversal)
SELECT 'UT'+RIGHT(RTRIM(RIGHT(@IDUNDDIDACT, 2)+1),4)
GO

create PROCEDURE GENERARIDMATRICULA
AS DECLARE @IDMATRICULA CHAR(7)
SET @IDMATRICULA=(SELECT MAX(IDMATRICULA)FROM Matricula)
SELECT LEFT(LTRIM(LEFT(@IDMATRICULA,4)+1),7)
go

--ALTER PROCEDURE GENERARIDMATRICULAE
--AS DECLARE @IDMATRICULA CHAR(7)
--SET @IDMATRICULA=(SELECT  max(IDMATRICULA) FROM Matricula)
--SELECT LEFT(LTRIM(LEFT(@IDMATRICULA,4)+1),7) 
--where LEFT(LTRIM(LEFT(@IDMATRICULA,4)+1),7)>=1001




