'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.296
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o vuelva a generar su proyecto de VS.
'''<summary>
'''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
Friend Module Resources
    
    Private resourceMan As Global.System.Resources.ResourceManager
    
    Private resourceCulture As Global.System.Globalization.CultureInfo
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend ReadOnly Property buscar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property buscar22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property buscar555() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar555", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property cancel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property cancel22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cancel22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property cancel55() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cancel55", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property eliminar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("eliminar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property eliminar222() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("eliminar222", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property eliminar55() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("eliminar55", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property entregaa() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("entregaa", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property guard555() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("guard555", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property guardd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("guardd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property guardd222() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("guardd222", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property modificar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("modificar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property modificar22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("modificar22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property modificar555() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("modificar555", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property monos() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("monos", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property nuebvo55() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("nuebvo55", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property nuevo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("nuevo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property nuevo22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("nuevo22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property otro() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("otro", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property otro22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("otro22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property salir() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("salir", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property salir22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("salir22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend ReadOnly Property salir555() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("salir555", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Module
